### ISSUE TITLE
Error running sample app under Scala3/ZIO2/zhttp2

### ISSUE THREAD

**Issue by carlosedp** [zio/zio-http#1344]
**Describe the bug**

While running an example project based on Scala 3.1.3, ZIO 2.0.0 and zhttp 2.0.0-RC9, I get:

```
❯ mill backend.run
[35/48] backend.compile
[info] compiling 1 Scala source to /Users/cdepaula/repos/scala-playground/zio-scalajs-stack/out/backend/compile.dest/classes ...
[info] done compiling
[48/48] backend.run
timestamp=2022-07-11T22:12:32.228802Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-11,9,8,6" java.lang.NoSuchMethodError: 'zio.ZIO zio.ZIO$.succeed(scala.Function0, java.lang.Object)'
	at zhttp.service.EventLoopGroup$Live$.nio(EventLoopGroup.scala:15)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
Exception in thread "zio-fiber-12,9,8,6" java.lang.NoSuchMethodError: 'zio.ZIO zio.ZIO$.succeed(scala.Function0, java.lang.Object)'
	at zhttp.service.ChannelFactory$.make(ChannelFactory.scala:9)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)
	at zhttp.service.Server$.start.macro(Server.scala:219)"
1 targets failed
backend.run subprocess failed
```

**To Reproduce**

My `Main.scala`:

```scala
import zhttp.http._
import zhttp.service.Server
import zio._

object HelloWorld extends ZIOAppDefault {

  // Create HTTP route
  val app: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "text" => Response.text("Hello World!")
    case Method.GET -> !! / "json" => Response.json("""{"greetings": "Hello World!"}""")
  }

  // Run it like any simple app
  def run =
    Server.start(8090, app)
}
```

**Expected behaviour**

The http server running.

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Scala: 3.1.3
 - JDK 11.0.11 (OpenJDK)

**Comment by carlosedp** [comment]
Sorry about the noise, just found-out on Discord that there is a binary dependency on zhttp - zio.

Ref. https://discord.com/channels/629491597070827530/819703129267372113/995509195015209000

**Comment by tusharmath** [comment]
You can try the snapshot version once.
