### ISSUE TITLE
WebSocketSimpleClient example on tag/v2.0.0-RC10

### ISSUE THREAD

**Issue by ihevcuk** [zio/zio-http#1384]
Example ends with error:

`SEVERE: Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:499)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at zhttp.service.ChannelFuture.$anonfun$execute$2(ChannelFuture.scala:27)`

Steps to reproduce the behaviour:
1. Create a new branch from tag: git checkout tags/v2.0.0-RC10 -b websocket-test
2. Open project in Intelij
3. Navigate to WebSocketSimpleClient example
4. Click green arrow and run the test

**Comment by gciuloaica** [comment]
@ihevcuk you have to update line 36 to: `httpSocket.toSocketApp.connect(url) *> ZIO.never` . If you need to shutdown the client then you have to add in implementation for it following websocket protocol.
