### ISSUE TITLE
Netty version bump introduced warnings while building native image for projects using zio-http

### ISSUE THREAD

**Issue by carlosedp** [zio/zio-http#2007]
**Describe the bug**
With a recent SNAPSHOT version of zio-http, netty bump started generating warnings while building GraalVM native image:

```
========================================================================================================================
GraalVM Native Image: Generating 'backend' (executable)...
========================================================================================================================
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
[1/7] Initializing...                                                                                    (8.0s @ 0.34GB)
...
```

This is a similar error to the Quarkus one here: https://github.com/quarkusio/quarkus/issues/29413

And the fix they implemented: https://github.com/quarkusio/quarkus/pull/29493

Apparently this is due to some changes in Netty 4.1.85 in https://github.com/netty/netty/commit/fe0b5ce16c4508387f999e530a85f2d968e90a3c

**To Reproduce**
Steps to reproduce the behaviour:

- Create an app using zio-http in a SNAPSHOT version with code below:

```scala
//> using scala "3.3.0-RC3"
//> using repository "sonatype:snapshots"
//> using lib "dev.zio::zio:2.0.9"
//> using lib "dev.zio::zio-http:0.0.4+6-79413b91-SNAPSHOT"

//> using packaging.graalvmArgs "--no-fallback"
//> using packaging.graalvmArgs "--enable-http"
//> using packaging.graalvmArgs "--enable-url-protocols=http,https"
//> using packaging.graalvmArgs "--install-exit-handlers"
//> using packaging.graalvmArgs "-Djdk.http.auth.tunneling.disabledSchemes="
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.DefaultFileRegion"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.epoll.Native"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.epoll.Epoll"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.epoll.EpollEventLoop"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.epoll.EpollEventArray"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.kqueue.KQueue"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.kqueue.KQueueEventLoop"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.kqueue.KQueueEventArray"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.kqueue.Native"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.unix.Limits"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.unix.Errors"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.channel.unix.IovArray"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.handler.codec.compression.ZstdOptions"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.incubator.channel.uring.Native"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.incubator.channel.uring.IOUring"
//> using packaging.graalvmArgs "--initialize-at-run-time=io.netty.incubator.channel.uring.IOUringEventLoopGroup"

import zio._
import zio.http._
import zio.http.model.Method

object HTTPServer extends ZIOAppDefault {

  val app: HttpApp[Any, Nothing] = Http.collect[Request] { case Method.GET -> !! / "text" =>
    Response.text("Hello World!")
  }

  override val run =
    Console.printLine("Server started in http://localhost:8080/text") *>
      Server.serve(app).provide(Server.default)
}
```

- Build native image using GraalVM with `scala-cli package --native-image -f httpserver.scala -o httpserver`

**Expected behaviour**
Application to build without warnings.

**Comment by carlosedp** [comment]
BTW, if using a newer snapshot like `0.0.4+22-9dfc438d-SNAPSHOT` I get the same build warnings but the application returns an error when I access it:

```
❯ ./httpserver
Server started in http://localhost:8080/text
Feb 21, 2023 12:13:01 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoClassDefFoundError: zio.Runtime$UnsafeAPI3
	at zio.http.netty.NettyRuntime.run(NettyRuntime.scala:38)
	at zio.http.netty.NettyRuntime.run$(NettyRuntime.scala:8)
	at zio.http.netty.NettyRuntime$$anon$1.run(NettyRuntime.scala:91)
	at zio.http.netty.server.ServerInboundHandler.writeResponse(ServerInboundHandler.scala:296)
	at zio.http.netty.server.ServerInboundHandler.channelRead0(ServerInboundHandler.scala:55)
	at zio.http.netty.server.ServerInboundHandler.channelRead0(ServerInboundHandler.scala:39)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

Might be related to https://github.com/zio/zio-http/issues/1982#issuecomment-1428562514

**Comment by vigoo** [comment]
@carlosedp that `java.lang.NoClassDefFoundError: zio.Runtime$UnsafeAPI3` error is because the latest snapshots require a latest snapshot of ZIO as well - there is a new method on `Runtime.unsafe` that we are using, not present in ZIO 2.0.9 yet.

We will go back to stable ZIO dependencies as soon as ZIO 2.0.10 is out.

**Comment by carlosedp** [comment]
> @carlosedp that `java.lang.NoClassDefFoundError: zio.Runtime$UnsafeAPI3` error is because the latest snapshots require a latest snapshot of ZIO as well - there is a new method on `Runtime.unsafe` that we are using, not present in ZIO 2.0.9 yet.
> 
> We will go back to stable ZIO dependencies as soon as ZIO 2.0.10 is out.

No problem, it was just an FYI on why my sample code used the 0.0.4+6 and not a newer one.
Thanks @vigoo

**Comment by jdegoes** [comment]
@vigoo Should we close this?

**Comment by vigoo** [comment]
I think the main part of the report is valid (the GraalVM warnings)

**Comment by vigoo** [comment]
@carlosedp I checked this issue, and not sure if there is anything to do on the zio-http side.

If you add the missing dependencies to your example, there are no warnings:

```
//> using lib "net.jpountz.lz4:lz4:1.3.0"
//> using lib "org.jboss.marshalling:jboss-marshalling:2.1.1.Final"
//> using lib "com.google.protobuf:protobuf-java:2.6.1"
```

Alternatively you can add graalvm exclusion configuration like in the linked quarkus PR.

**Comment by jdegoes** [comment]
Closed, please re-open if it is related to _ZIO HTTP_.

**Comment by carlosedp** [comment]
@vigoo revisiting this, I understand the issue is related to zio-http lib and not my own code.

I don't depend on lz4, jboss-marshalling and protobuf-java, it's a dependency of Netty which is zio-http dependency therefore generating the error on zio-http.

Likewise Quarkus, they added the exclusion to Quarkus itself and not the need to every user created code add the dependency libs or implement the exclusion.

Wouldn't be better to have zio-http filter-out these? Dunno if it's possible tho.

**Comment by vigoo** [comment]
@carlosedp I don't think it is a good idea to modify the underlying Netty library by overridding some of its functionalities like in the linked Quarkus PR. Even if you are not using these modules and they are not directly needed for zio-http, other libraries also depend on Netty and those, or the applications themselves, may depend on them. 

Using zio-http with GraalVM is just one use case of many possible.

Also it is only a warning from GraalVM, not a failure, and it has a very easy fix (either including the dependencies or writing exclusions to the app specific graalVM configuration). So I still believe this is not something we should address in zio-http.

**Comment by carlosedp** [comment]
Yes, I agree these things are a burden to maintain in the middleman.
Thanks for taking the time to explain it better @vigoo!
