### ISSUE TITLE
`Authorization.toAuthorization` throws `java.lang.IllegalArgumentException`

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-http#2045]
**Describe the bug**
Using `zio.http.model.headers.values.Authorization.toAuthorization(...)` to extract credentials throws a `java.lang.IllegalArgumentException` when a non-base64 encoded string is used with the `Basic` prefix

**To Reproduce**
```scala
import zio.http.model.headers.values.Authorization

val creds = Authorization.toAuthorization("Basic not-base64")
```
throws:
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 2d
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at zio.http.model.headers.values.Authorization$.parseBasic(Authorization.scala:88)
	at zio.http.model.headers.values.Authorization$.toAuthorization(Authorization.scala:79)
        ...
```

**Expected behaviour**

Method to return `InvalidAuthorizationValue` or (less ideally) to be annotated with `@throws`

**Comment by vigoo** [comment]
According to https://www.rfc-editor.org/rfc/rfc7617 the `Basic` auth header is always supposed to be base64 of the `user:password` string so I think this is the correct behavior.

**Comment by kyri-petrou** [comment]
@vigoo I agree it's not a valid value, but shouldn't the method return `InvalidAuthorizationValue` like in line 92?

https://github.com/zio/zio-http/blob/57aab0e0d6a6b4ac6b659d91b3fe877696da3798/zio-http/src/main/scala/zio/http/model/headers/values/Authorization.scala#L87-L94

**Comment by vigoo** [comment]
Yes that would be better! Will fix

**Comment by kyri-petrou** [comment]
Thanks 🙏
