### ISSUE TITLE
ClientServer Example Throwing Error

### ISSUE THREAD

**Issue by jamesward** [zio/zio-http#2168]
**Describe the bug**
The [ClientServer](https://github.com/zio/zio-http/blob/main/zio-http-example/src/main/scala/example/ClientServer.scala) example throws an error when I make a request to `/`
```
zio-http-native-client-bug[ERROR] May 09, 2023 11:36:57 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
zio-http-native-client-bug[ERROR] WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
zio-http-native-client-bug[ERROR] java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.writeAndFlush(Object)" because "ctx" is null
zio-http-native-client-bug[ERROR] 	at zio.http.netty.NettyBodyWriter$.write$$anonfun$3$$anonfun$1(NettyBodyWriter.scala:51)
zio-http-native-client-bug[ERROR] 	at zio.http.netty.AsyncBodyReader.connect$$anonfun$1(AsyncBodyReader.scala:43)
zio-http-native-client-bug[ERROR] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
zio-http-native-client-bug[ERROR] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
zio-http-native-client-bug[ERROR] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
zio-http-native-client-bug[ERROR] 	at zio.Chunk$Arr.foreach(Chunk.scala:1672)
zio-http-native-client-bug[ERROR] 	at zio.http.netty.AsyncBodyReader.connect(AsyncBodyReader.scala:44)
zio-http-native-client-bug[ERROR] 	at zio.http.netty.NettyResponse$.$anonfun$1(NettyResponse.scala:73)
zio-http-native-client-bug[ERROR] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
zio-http-native-client-bug[ERROR] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
zio-http-native-client-bug[ERROR] 	at zio.http.netty.NettyBodyWriter$.write$$anonfun$3(NettyBodyWriter.scala:52)
zio-http-native-client-bug[ERROR] 	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
zio-http-native-client-bug[ERROR] 	at zio.ZIO$.suspendSucceed$$anonfun$1(ZIO.scala:4586)
zio-http-native-client-bug[ERROR] 	at zio.UnsafeVersionSpecific.implicitFunctionIsFunction$$anonfun$1(UnsafeVersionSpecific.scala:27)
zio-http-native-client-bug[ERROR] 	at zio.Unsafe$.unsafe(Unsafe.scala:37)
zio-http-native-client-bug[ERROR] 	at zio.ZIOCompanionVersionSpecific.succeed$$anonfun$1(ZIOCompanionVersionSpecific.scala:162)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:904)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
zio-http-native-client-bug[ERROR] 	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
zio-http-native-client-bug[ERROR] 	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
```

**To Reproduce**
1. Run the `ClientServer` example
2. Make a request to `/`

**Expected behaviour**
It should return the response

Assembling a new response works:
```
      Client.request(url).flatMap { response =>
        response.body.asString.map { body =>
          Response.html(body)
        }
      }
```

Using zio-http 3.0.0-RC1.

**Comment by andrzejressel** [comment]
Haven't we just fixed it? https://github.com/zio/zio-http/issues/2157

**Comment by jamesward** [comment]
Oh nice!  Looks like it.
