### ISSUE TITLE
Nullpointer when aliasing a HTTP val

### ISSUE THREAD

**Issue by ruurtjan** [zio/zio-http#2222]
**Describe the bug**
ZIO HTTP throws a nullpointer exception when starting an app with an aliased HTTP value.

**To Reproduce**
```scala
import zio.*
import zio.http.*

object ZioReproducer extends ZIOAppDefault {
  def run: ZIO[Environment, Any, Any] =
    Server.serve(
      // userApp.withDefaultErrorResponse // This works fine
      http.withDefaultErrorResponse // This fails
    ).provide(
      Server.default,
    )

  val http = userApp // This somehow crashes the app

  val userApp = 
    Http.collect[Request] { case Method.GET -> Root / "user" / name / "greet" =>
      Response.text(s"Welcome to the ZIO party! ${name}")
    }
}
```

```
[info] running (fork) ZioReproducer
[info] timestamp=2023-05-31T12:08:12.373551Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.NullPointerException: Cannot invoke "zio.http.Http.withDefaultErrorResponse(Object, scala.$less$colon$less, scala.$less$colon$less)" because the return value of "ZioReproducer$.http()" is null
[info] 	at ZioReproducer$.run(ZioReproducer.scala:8)
[info] 	at zio.ZIOAppPlatformSpecific.$anonfun$3$$anonfun$1$$anonfun$1(ZIOAppPlatformSpecific.scala:23)
[info] 	at zio.Scope$ExtendPartiallyApplied$.apply$extension(Scope.scala:172)
[info] 	at zio.Scope$UsePartiallyApplied$.apply$extension(Scope.scala:177)
[info] 	at zio.ZIO$ScopedPartiallyApplied$.apply$extension$$anonfun$7(ZIO.scala:5267)"
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 2 s, completed 31 May 2023, 14:08:12
```

Relevant sections from my `build.sbt`:
```scala

Global / scalaVersion := "3.2.1"

lazy val zioVersion    = "2.0.12"

Global / libraryDependencies ++= Seq(
  // Effect systems
  "dev.zio" %% "zio"         % zioVersion,
  "dev.zio" %% "zio-streams" % zioVersion,

  // HTTP server
  "dev.zio" %% "zio-json" % "0.5.0",
  "dev.zio" %% "zio-http"    % "3.0.0-RC2",

  // Testing
  "dev.zio" %% "zio-test"     % zioVersion % "test",
  "dev.zio" %% "zio-test-sbt" % zioVersion % "test"
)
```

**Expected behaviour**
Succeed, or fail at compile-time.

**Comment by guymers** [comment]
Compiling with Scala 2.13

```
[info] compiling 1 Scala source to .../target/scala-2.13/classes ...
[warn] .../src/main/scala/Main.scala:13:14: Reference to uninitialized value userApp
[warn]   val http = userApp // This somehow crashes the app
[warn]              ^
[warn] one warning found
```

**Comment by vigoo** [comment]
`userApp` as the warning also says, gets initialized _after_ `http` (it goes top to bottom). So `http` becomes `null` and it fails when you first reference it in your `run` method. Directly using `userApp` there works because at the time `run` runs, it is already initialized.
