### ISSUE TITLE
onUnhandledInboundException when creating Body from failed stream starting with 3.0.0-RC1

### ISSUE THREAD

**Issue by odzhychko** [zio/zio-http#2245]
**Describe the bug**

When creating a `Body.fromStream` and the given stream is failed, an `onUnhandledInboundException` is warned about from Netty, the failure is not correctly propagated and the application does not terminate.

**To Reproduce**

Run the following code with version `3.0.0-RC`.

```scala
object Main extends ZIOAppDefault {
  val url = "https://httpbin.org/put"

  private val failingStream = ZStream.fail(new RuntimeException("Some error"))

  override val run = Client.request(url, method = PUT, content = Body.fromStream(failingStream))
    .provide(Client.default)

}
```

**Expected behaviour**

In version `0.0.5` the exception is logged and the application terminates.

```
timestamp=2023-06-09T09:58:00.954843847Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.RuntimeException: Some error
  at Main$.$anonfun$failingStream$1(Main.scala:9)
  at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3146)
  at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)
  at <empty>.Main.run(Main.scala:11)
  at <empty>.Main.run(Main.scala:12)"

Process finished with exit code 1
```

But in `3.0.0-RC1` and `3.0.0-RC2` the failed stream is not handle correctly. A warning is produced and the application does not terminate.

```
Jun 09, 2023 12:02:34 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Some error
	at Main$.$anonfun$failingStream$1(Main.scala:9)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3146)
	at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
```

**Comment by jdegoes** [comment]
@vigoo What do you think the correct behavior is here?

**Comment by vigoo** [comment]
As it is supposed to fully consume the input stream (it returns with a `Response`) I think `request` should fail with the stream failure here.
