### ISSUE TITLE
Potential "NoSuchElementException: None.get" in RequestHandlerMiddlewares.beautifyErrors

### ISSUE THREAD

**Issue by aboisvert** [zio/zio-http#2442]
An exception can be thrown by the RequestHandlerMiddlewares.beautifyErrors if httpError is None

This is on zip-http 3.0-RC2 release

Full stacktrace
```
21:18:04.793 [zio-default-blocking-2] ERROR email.captcha.Main - timestamp=2023-09-11T21:18:04.792939-07:00 level=ERROR thread=zio-fiber-72 message="onFailure Exception in thread "zio-fiber-72" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at zio.http.internal.middlewares.HtmlErrorResponses.htmlResponse$1(HtmlErrorResponses.scala:37)
	at zio.http.internal.middlewares.HtmlErrorResponses.replaceErrorResponse(HtmlErrorResponses.scala:54)
	at zio.http.internal.middlewares.HtmlErrorResponses.replaceErrorResponse$(HtmlErrorResponses.scala:24)
	at zio.http.RequestHandlerMiddlewares$.replaceErrorResponse(RequestHandlerMiddlewares.scala:397)
	at zio.http.RequestHandlerMiddlewares.beautifyErrors$$anonfun$1(RequestHandlerMiddlewares.scala:47)
	at zio.http.RequestHandlerMiddlewares$$anon$2.apply$$anonfun$2$$anonfun$1(RequestHandlerMiddlewares.scala:88)
	at zio.http.Handler.map$$anonfun$1$$anonfun$1(Handler.scala:325)
	at zio.http.Handler$.succeed$$anonfun$1(Handler.scala:840)
	at zio.http.Handler$$anon$15.apply(Handler.scala:703)
	at zio.http.Handler$$anon$5.apply$$anonfun$4(Handler.scala:304)
	at email.captcha.Main.run.httpApp(Main.scala:59)
	at email.captcha.Main.run(Main.scala:66)
	at email.captcha.Main.run(Main.scala:70)
	at email.captcha.Main.run(Main.scala:75)"
```

**Comment by aboisvert** [comment]
The culprit code is:

```
          div(
            response.httpError.get.foldCause(div()) { throwable =>
              div(h3("Cause:"), pre(prettify(throwable)))
            },
```

which calls `httpError.get` indiscriminately, without a guard to check for Option.isSome

**Comment by TomTriple** [comment]
This code does not exist anymore in master

**Comment by aboisvert** [comment]
Indeed, this is no longer valid.  Thanks for pointing this out.
