### ISSUE TITLE
Websocket crashes with CorruptedWebSocketFrameException RSV !=0

### ISSUE THREAD

**Issue by NiklasVonMinckwitz** [zio/zio-http#2691]
**Describe the bug**

I tried to setup websockets with zio stream using tapir and found a bug which I already reported on the tapir github thinking it was a tapir problem but after further investigation I realized the zio-http websocket example created the same bug for me.

I can connect to the socket with python websockets but as soon as I send "FOO" the following error message is printed and the connection closes.
```
timestamp=2024-02-21T12:07:17.543802Z level=WARN thread=#zio-fiber-42 message="Fatal exception in Netty" cause="Exception in thread "zio-fiber-" io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: RSV != 0 and no extension negotiated, RSV:4
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:427)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:423)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:197)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:218)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:296)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)"
```

**To Reproduce**
run the minimal example 
```scala
import zio._

import zio.http.ChannelEvent.Read
import zio.http._
import zio.http.codec.PathCodec.string

object WebSocketEcho extends ZIOAppDefault {
  private val socketApp: WebSocketApp[Any] =
    Handler.webSocket { channel =>
      channel.receiveAll {
        case Read(WebSocketFrame.Text("FOO")) =>
          channel.send(Read(WebSocketFrame.Text("BAR")))
        case Read(WebSocketFrame.Text("BAR")) =>
          channel.send(Read(WebSocketFrame.Text("FOO")))
        case Read(WebSocketFrame.Text(text))  =>
          channel.send(Read(WebSocketFrame.Text(text))).repeatN(10)
        case _                                =>
          ZIO.unit
      }
    }

  private val app: HttpApp[Any] =
    Routes(
      Method.GET / "greet" / string("name") -> handler { (name: String, req: Request) =>
        Response.text(s"Greetings {$name}!")
      },
      Method.GET / "subscriptions"          -> handler(socketApp.toResponse),
    ).toHttpApp

  override val run = Server.serve(app).provide(Server.default)
}
```
with zio 2.0.21 and zio-http 3.0.0-RC4 and send "FOO" via some websocket client.

**Expected behaviour**
"BAR" is sent back by websocket server

**Screenshots**
![kitty Screenshot 2024-02-21 at 13 15 50@2x](https://github.com/zio/zio-http/assets/6071531/0269b017-fa6e-4b4f-b2fa-67da4371185e)

**Desktop (please complete the following information):**
 - OSX Sonoma 14.2.1
 - Adoptopenjdk-20.0.2

**Comment by NiklasVonMinckwitz** [comment]
Is there some more information I can provide to help with further debugging? Or can nobody replicate the bug? Maybe someone could point me towards a direction on how to implement a fix? I’m not super experienced with ZIO but I would like to help as much as I can!

**Comment by NiklasVonMinckwitz** [comment]
So after quite some debugging with WireShark I found the problem and it has absolutely nothing to do with zio-http but instead with parental control being enabled on my Mac. This leads to websocket frames being rerouted to port 10011 instead of 8080. The HTTP handshake succeeds but websocket request wont get through. Instead a second HTTP GET Upgrade request is sent to 8080 which netty subsequently tries to decode as a websocket frame - in vain. To solve this problem I just had to change my port to 8081. Now everything is working flawlessly! [Here](https://discussions.apple.com/thread/250500940?sortBy=best) is the resource that gave me the hint.

**Comment by visox** [comment]
strange i do have also this problem on ubuntu and port 8090

edit: or maybe its a bit different
```
timestamp=2024-07-21T17:29:32.994284529Z level=WARN thread=#zio-fiber-415373534 message="Fatal exception in Netty" cause="Exception in thread "zio-fiber-" java.lang.IllegalArgumentException: Unsupported HTTP version: HTTP/2.0
        at zio.http.netty.server.ServerInboundHandler.makeZioRequest(ServerInboundHandler.scala:212)
        at zio.http.netty.server.ServerInboundHandler.channelRead0(ServerInboundHandler.scala:87)
        at zio.http.netty.server.ServerInboundHandler.channelRead0(ServerInboundHandler.scala:74)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
```
...
```
[33m19:19:03.187 WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
ESC[m java.lang.IllegalArgumentException: Unsupported HTTP version: HTTP/2.0
        at zio.http.netty.server.ServerInboundHandler.makeZioRequest(ServerInboundHandler.scala:212) ~[dev.zio.zio-http_3-3.0.0-RC9.jar:3.0.0-RC9]
        at zio.http.netty.server.ServerInboundHandler.channelRead0(ServerInboundHandler.scala:87) ~[dev.zio.zio-http_3-3.0.0-RC9.jar:3.0.0-RC9]
        at zio.http.netty.server.ServerInboundHandler.channelRead0(ServerInboundHandler.scala:74) ~[dev.zio.zio-http_3-3.0.0-RC9.jar:3.0.0-RC9]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[io.netty.netty-transport-4.1.109.Final.jar:4.1.109.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.netty-transport-4.1.109.Final.jar:4.1.109.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.109.Final.jar:4.1.109.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.109.Final.jar:4.1.109.Final]
```

the app still appears to work
