### ISSUE TITLE
ClassCastException when running ServerSentEventEndpoint Example

### ISSUE THREAD

**Issue by khajavi** [zio/zio-http#2695]
1. Run the `ServerSentEventEndpoint` from the `example` project.
2. Run `curl -N "http://127.0.0.1:8080/sse" -i`

Expected:
The curl should print the events created by the server to the console

Current Behaviour:
The curl prints the following message:

```bash
> curl -N "http://127.0.0.1:8086/sse" -i
HTTP/1.1 200 OK
content-type: application/json
transfer-encoding: chunked

curl: (18) transfer closed with outstanding read data remaining
```

The app prints these exceptions:

```scala
Feb 23, 2024 11:56:28 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ClassCastException: class zio.http.ServerSentEvent cannot be cast to class java.lang.Byte (zio.http.ServerSentEvent is in unnamed module of loader 'app'; java.lang.Byte is in module java.base of loader 'bootstrap')
	at scala.runtime.BoxesRunTime.unboxToByte(BoxesRunTime.java:91)
	at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:80)
	at zio.Chunk$Singleton.toArray(Chunk.scala:1818)
	at zio.Chunk.toArray(Chunk.scala:1002)
	at zio.Chunk.toArray(Chunk.scala:873)
	at zio.http.netty.NettyBodyWriter$.$anonfun$writeAndFlush$14(NettyBodyWriter.scala:123)
	at zio.http.netty.NettyFutureExecutor$.$anonfun$make$1(NettyFutureExecutor.scala:67)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:904)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:948)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:478)
```

Please note that I have written another server-sent example that works properly:

```scala
object ServerSentExample extends ZIOAppDefault {

  val stream: ZStream[Any, Nothing, ServerSentEvent] =
    ZStream.repeatWithSchedule(ServerSentEvent(ISO_LOCAL_TIME.format(LocalDateTime.now)), Schedule.spaced(1.second))
    
  val app =
    Routes(
      Method.GET / "sse" ->  handler {
          Response.fromServerSentEvents(stream)
      }
    ).toHttpApp
  def run = Server.serve(app).provide(Server.default)
}
```

**Comment by jdegoes** [comment]
/bounty $150 for identifying and fixing the underlying class cast exception, and having a test to ensure it doesn't happen anymore.

**Comment by varshith257** [comment]
/attempt #2695

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx18dxm1001kmp09j1hw43l0/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
