### ISSUE TITLE
OpenAPIGen fails on PathCodec.empty Root path

### ISSUE THREAD

**Issue by tmkontra** [zio/zio-http#3110]
**Describe the bug**
The root endpoint (PathCodec.empty) causes OpenAPIGen to throw an exception

**To Reproduce**

Source code:

```
object MyServer {
  import zio.http.codec.PathCodec._

  private val indexRoute =
    Endpoint(RoutePattern.GET / PathCodec.empty)
      .out[String]

  def routes: Routes[Env, Nothing] =
    Routes(
      indexRoute.implement(_ => ZIO.service[MyService].map(_.show()))
    )

  def endpoints = Seq(indexRoute)

  def openapi = OpenAPIGen.fromEndpoints(title="My API", version="0.1", endpoints)

  def apply() =
    routes ++ SwaggerUI.routes(PathCodec.empty / "docs", openapi)
}
```

Stack trace:

```
timestamp=2024-09-07T04:33:14.742410Z level=ERROR thread=#zio-fiber-1112602523 message="" cause="Exception in thread "zio-fiber-345660099" java.lang.Exception: Invalid path: 
	at zio.http.endpoint.openapi.OpenAPIGen$.buildPath$1$$anonfun$1(OpenAPIGen.scala:556)
	at scala.Option.getOrElse(Option.scala:201)
	at zio.http.endpoint.openapi.OpenAPIGen$.buildPath$1(OpenAPIGen.scala:556)
	at zio.http.endpoint.openapi.OpenAPIGen$.path$7(OpenAPIGen.scala:514)
	at zio.http.endpoint.openapi.OpenAPIGen$.gen(OpenAPIGen.scala:799)
	at zio.http.endpoint.openapi.OpenAPIGen$.fromEndpoints$$anonfun$3(OpenAPIGen.scala:485)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at zio.http.endpoint.openapi.OpenAPIGen$.fromEndpoints(OpenAPIGen.scala:485)
	at zio.http.endpoint.openapi.OpenAPIGen$.fromEndpoints(OpenAPIGen.scala:491)
	at http.MilemarkerServer$.openapi(MilemarkerServer.scala:13)
	at http.MilemarkerServer$.apply(MilemarkerServer.scala:16)
	at run.Application$.run$$anonfun$1$$anonfun$1$$anonfun$3(Application.scala:33)
	at run.Application.run(Application.scala:32)
	at run.Application.run(Application.scala:35)"

Process finished with exit code 1
```

**Expected behaviour**
OpenAPIGen succeeds

**Desktop (please complete the following information):**
 - OS: macOS monterey 12.7.6 (intel)
- ZIO Version: 2.1.1
- ZIO Http Version: 3.0.0-RC9

**Comment by pawelsadlo** [comment]
/attempt #3110

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/pawelsadlo) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @pawelsadlo | 1 ZIO bounty | <div align="center">Scala</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0wd79ee000uml032rx77wrm/cancel-attempt) |
