### ISSUE TITLE
PrematureChannelClosureException when uploading big file

### ISSUE THREAD

**Issue by madoxas** [zio/zio-http#3263]
I'm following the guide of how to upload video file to youtube. I'm stuck at step 3 upload the file: https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol#Upload_File

I have a file of about 10G and after around 1min I get this exception:
```
$ scala-cli upload.scala
Compiling project (Scala 3.6.2, JVM (17))
Compiled project (Scala 3.6.2, JVM (17))
timestamp=2024-12-26T13:46:59.316608438Z level=ERROR thread=#zio-fiber-1754675907 message="" cause="Exception in thread "zio-fiber-85847178" io.netty.handler.codec.PrematureChannelClosureException: Channel closed while executing the request. This is likely caused due to a client connection misconfiguration
	at zio.http.netty.client.NettyClientDriver$.<clinit>(NettyClientDriver.scala:194)
	at zio.http.ZClientPlatformSpecific.live(ZClientPlatformSpecific.scala:30)
	at zio.http.ZClientPlatformSpecific.live$(ZClientPlatformSpecific.scala:9)
	at zio.http.ZClient$.live(ZClient.scala:268)
	at zio.http.ZClientPlatformSpecific.default$$anonfun$4(ZClientPlatformSpecific.scala:45)
	at zio.ZLayer$.zio$ZLayer$ZLayerProvideSomeOps$$$_$$greater$greater$greater$extension$$anonfun$2(ZLayer.scala:2080)
	at zio.ZLayer.scope$$anonfun$6$$anonfun$1(ZLayer.scala:431)
	at zio.ZLayer.build$$anonfun$2$$anonfun$1(ZLayer.scala:129)
	at <empty>.Uploader.app(upload.scala:22)
	at <empty>.Uploader.app(upload.scala:23)
	at <empty>.Uploader.run(upload.scala:25)"
```

This is the code:
```scala
//> using scala "3"
//> using dependency "dev.zio::zio-http::3.0.1"
//> using dependency "dev.zio::zio::2.1.14"

import zio._
import zio.http._
import java.io.File

object Uploader extends ZIOAppDefault {

  val accessToken: String = ??? 
  val location: URL = ??? 

  val headers = Headers(
    Header.Authorization.Bearer(accessToken),
    Header.ContentType(MediaType.application.`octet-stream`)
  )

  val app = for {
    body   <- Body.fromFile(new File("video.mp4"))
    client <- ZIO.service[Client]
    _ <- client.batched.addHeaders(headers).request(Request.put(location, body))
  } yield ()

  override val run = app.provide(Client.default)

}
```

In system monitor I can see that the actual upload is happening at around 10MiB/s until it's stopped by this exception.
With smaller files (~100mb) all works fine.

What I'm doing wrong? How can I debug this?

**Comment by madoxas** [comment]
I was missing [idleTimeout](https://github.com/zio/zio-http/blob/6d9dce1791d9e25ad207f89cfafdf973c08c1eaa/zio-http/shared/src/main/scala/zio/http/ZClient.scala#L539) configuration - the default is too low for big uploads.
Closing the issue.
