### ISSUE TITLE
"java.lang.UnsupportedOperationException: direct buffer" when calling request.getBody

### ISSUE THREAD

**Issue by adamw** [zio/zio-http#644]
**To Reproduce**

Calling `request.getBody` when the request body is non-empty ends up with an exception.

Run:

```scala
import zio._
import zhttp.http._
import zhttp.service.Server

object ZioHttpTest extends App {
  val app = Http.collectM[Request] { case r =>
    r.getBody.map(_ => Response.text("Hello World!"))
  }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
}
```

And invoke:

```
curl -X POST -d "abc" http://localhost:8090
```

I'm getting:

```
<html>
  <head>
  </head>
  <body>
   <h1>Internal Server Error</h1>
   <pre><div>java.lang.UnsupportedOperationException: direct buffer</div><div>	at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:226)</div><div>	at io.netty.buffer.CompositeByteBuf.array(CompositeByteBuf.java:793)</div><div>	at zhttp.http.Request.$anonfun$getBody$2(Request.scala:25)</div><div>	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)</div><div>	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)</div><div>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)</div><div>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)</div><div>	at java.base/java.lang.Thread.run(Thread.java:832)</div></pre>
  </body>
</html>
```

**Desktop (please complete the following information):**

This came up when migrating tapir to use latest zhttp in https://github.com/softwaremill/tapir/pull/1686 (cc @guizmaii)

```
"io.d11" %% "zhttp" % "1.0.0.0-RC18"
```

**Comment by tusharmath** [comment]
Thanks @adamw. Looking into this.
