### ISSUE TITLE
Http.collectM crashes on scala 3

### ISSUE THREAD

**Issue by palanga** [zio/zio-http#655]
A simple app like this:

```scala
import zio.*
import zhttp.http.*
import zhttp.service.Server

object Example extends App:

  val app = Http.collectM[Request] { case Method.GET -> !! / "hola" => ZIO succeed Response.text("hola") }

  def run(args: List[String]) = Server.start(8090, app).exitCode
```

when calling that endpoint it responds successfully but crashes immediately with:

```
Fiber failed.
An unchecked error was produced.
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at zhttp.service.HttpRuntime.unsafeRun$$anonfun$4$$anonfun$2$$anonfun$2(HttpRuntime.scala:24)
	at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:344)
	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for dynamic parameter 0: class java.lang.Object is not a subtype of interface io.netty.util.concurrent.Future
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.checkDescriptor(AbstractValidatingLambdaMetafactory.java:325)
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:311)
	at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:535)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:147)
	... 10 more

Fiber:Id(1639675798870,6) was supposed to continue to:
  a future continuation at zhttp.service.HttpRuntime.6$$anonfun(HttpRuntime.scala:23)
  a future continuation at zio.Runtime.unsafeRunWith$$anonfun$2(Runtime.scala:214)

Fiber:Id(1639675798870,6) execution trace:
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zhttp.service.HttpRuntime.7$$anonfun(HttpRuntime.scala:23)
  at zio.ZIO.$times$greater$$anonfun$1(ZIO.scala:95)

Fiber:Id(1639675798870,6) was spawned by: <empty trace>
Fiber failed.
An unchecked error was produced.
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at zhttp.service.HttpRuntime.unsafeRun$$anonfun$4$$anonfun$2$$anonfun$2(HttpRuntime.scala:24)
	at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:344)
	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Fiber:Id(1639675837156,8) was supposed to continue to:
  a future continuation at zhttp.service.HttpRuntime.6$$anonfun(HttpRuntime.scala:23)
  a future continuation at zio.Runtime.unsafeRunWith$$anonfun$2(Runtime.scala:214)

Fiber:Id(1639675837156,8) execution trace:
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zhttp.service.HttpRuntime.7$$anonfun(HttpRuntime.scala:23)
  at zio.ZIO.$times$greater$$anonfun$1(ZIO.scala:95)

Fiber:Id(1639675837156,8) was spawned by: <empty trace>
Fiber failed.
An unchecked error was produced.
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at zhttp.service.HttpRuntime.unsafeRun$$anonfun$4$$anonfun$2$$anonfun$2(HttpRuntime.scala:24)
	at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:344)
	at zio.internal.FiberContext.evaluateLater$$anonfun$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Fiber:Id(1639675841972,10) was supposed to continue to:
  a future continuation at zhttp.service.HttpRuntime.6$$anonfun(HttpRuntime.scala:23)
  a future continuation at zio.Runtime.unsafeRunWith$$anonfun$2(Runtime.scala:214)

Fiber:Id(1639675841972,10) execution trace:
  at zio.ZIO$.effectTotal$$anonfun$1(ZIO.scala:2819)
  at zhttp.service.HttpRuntime.7$$anonfun(HttpRuntime.scala:23)
  at zio.ZIO.$times$greater$$anonfun$1(ZIO.scala:95)

Fiber:Id(1639675841972,10) was spawned by: <empty trace>

```

**Desktop:**
 - OS: macOS 10.15.7

**Additional context**
`build.sbt` file:

```scala
ThisBuild / scalaVersion := "3.1.0"

libraryDependencies += "dev.zio" %% "zio"   % "1.0.12"
libraryDependencies += "io.d11"  %% "zhttp" % "1.0.0.0-RC18"

```

**Comment by tusharmath** [comment]
duplicate #613 

@palanga I think this is fixed in #608 Can you try the latest snapshot once. 
Will be making a release next week with this fix.

**Comment by palanga** [comment]
Sorry for the duplicate guys. Is there a test for this case? I can try to write one.

**Comment by amitksingh1490** [comment]
> 

tests were already there but our ci jdk was fixed at java8. we updated the matrix in this PR only.
