### ISSUE TITLE
Streaming response body using `HttpData.fromStream` fails

### ISSUE THREAD

**Issue by kubinio123** [zio/zio-http#825]
`zio-http`: `1.0.0.0-RC22`
`zio`, `zio-streams`: `1.0.13` 

So this is more or less "echo" endpoint, takes body and streams it back:
```
import zhttp.http._
import zhttp.service.Server
import zio._
import zio.stream.ZStream

object ZioHttpVanilla extends App {
  val app: Http[Any, Nothing, Request, Response] =
    Http.route[Request] { req =>
      Http.succeed {
        val length = req.getContentLength.getOrElse(throw new RuntimeException)
        val body = ZStream.fromEffect(req.getBody).flattenChunks
        Response(status = Status.OK, headers = Headers.contentLength(length), data = HttpData.fromStream(body))
      }
    }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
}
```

invocation:

```
curl --request POST \
  --url http://localhost:8090/ \
  --header 'Content-Type: text/plain' \
  --data jacob
```

results in:

```
Fiber failed.
A checked error was not handled.
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1383)
	at io.netty.buffer.AbstractByteBuf.checkDstIndex(AbstractByteBuf.java:1409)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:1062)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:2031)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:49)
	at io.netty.buffer.ByteBufUtil.getBytes(ByteBufUtil.java:1336)
	at io.netty.buffer.ByteBufUtil.getBytes(ByteBufUtil.java:1309)
	at io.netty.buffer.ByteBufUtil.getBytes(ByteBufUtil.java:1301)
	at zhttp.http.Request.$anonfun$getBody$2(Request.scala:33)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:496)
	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:781)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

Fiber:Id(1642076579236,7) was supposed to continue to:
  a future continuation at zio.stream.ZStream$BufferedPull.pullElement(ZStream.scala:4534)
  a future continuation at scala.$less$colon$less$$anon$1.apply(typeConstraints.scala:148)
  a future continuation at zio.stream.ZStream.mapChunksM(ZStream.scala:2056)
  a future continuation at zio.stream.ZStream.runManaged(ZStream.scala:2648)
  a future continuation at zio.ZManaged.mapM(ZManaged.scala:517)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:291)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:291)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1089)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1088)
  a future continuation at zhttp.service.server.content.handlers.ServerResponseHandler.writeStreamContent(ServerResponseHandler.scala:71)

Fiber:Id(1642076579236,7) execution trace:
  at zio.stream.ZStream$BufferedPull.update(ZStream.scala:4523)
  at zio.stream.ZStream$.fromEffect(ZStream.scala:3830)
  at zhttp.http.Request.getBody(Request.scala:33)
  at zhttp.http.Request.getBody(Request.scala:33)
  at zhttp.service.Handler$$anon$1.getBodyAsByteBuf(Handler.scala:36)
  at zio.ZIO.flatten(ZIO.scala:700)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.stream.ZStream$BufferedPull.ifNotDone(ZStream.scala:4516)
  at zio.ZRef$Atomic.get(ZRef.scala:203)
  at zio.ZIO.flatten(ZIO.scala:700)
  at zio.ZRef$Atomic.modify(ZRef.scala:215)
  at zio.stream.ZStream$BufferedPull.ifNotDone(ZStream.scala:4516)
  at zio.ZRef$Atomic.get(ZRef.scala:203)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:561)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at zio.ZManaged.flatMap(ZManaged.scala:337)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.ZManaged$.succeed(ZManaged.scala:2497)
  at zio.ZManaged.flatMap(ZManaged.scala:336)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:565)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at zio.stream.ZStream$BufferedPull$.make(ZStream.scala:4556)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.stream.ZStream$BufferedPull$.make(ZStream.scala:4555)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:561)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.ZManaged$.fromEffect(ZManaged.scala:1883)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:565)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:561)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:561)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZManaged.use(ZManaged.scala:1089)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1375)
  at zio.ZRef$.make(ZRef.scala:756)

Fiber:Id(1642076579236,7) was spawned by:

Fiber:Id(1642076579231,6) was supposed to continue to:
  a future continuation at zhttp.service.HttpRuntime.unsafeRun(HttpRuntime.scala:23)
  a future continuation at zio.Runtime.unsafeRunAsyncCancelable(Runtime.scala:111)

Fiber:Id(1642076579231,6) execution trace:
  at zhttp.service.HttpRuntime.unsafeRun(HttpRuntime.scala:22)

Fiber:Id(1642076579231,6) was spawned by: <empty trace>
```

The following code works fine with `zio-http:1.0.0.0-RC21` (with specifying `Response[Any, Throwable]` types).

**Comment by amitksingh1490** [comment]
Thanks for reporting this, I am able to reproduce it locally will create a PR for Fix soon.
