### ISSUE TITLE
Possible runtime dependency conflict manifests in Kubernetes deployment

### ISSUE THREAD

**Issue by etherline** [zio/zio-http#956]
**Describe the bug**
The issue appears to be a runtime dependency conflict between zio-http and zio-core when deployed to Kubernetes. The pod fails to start and shows an Error status. The only log entry is as follows:

```
_timestamp=2022-02-04T16:38:24.257214Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-1" java.lang.NoSuchMethodError: 'zio.ZManaged zio.ZManaged$.service(izumi.reflect.Tag, zio.package$IsNotIntersection, java.lang.Object)'
	at zhttp.service.Server$.make(Server.scala:216)
	at zhttp.service.Server.make(Server.scala:38)
	at zhttp.service.Server.make$(Server.scala:35)
	at zhttp.service.Server$Concat.make(Server.scala:140)
	at zhttp.service.Server.start(Server.scala:41)
	at zhttp.service.Server.start$(Server.scala:40)
	at zhttp.service.Server$Concat.start(Server.scala:140)
	at zhttp.service.Server.startDefault(Server.scala:47)
	at zhttp.service.Server.startDefault$(Server.scala:46)
	at zhttp.service.Server$Concat.startDefault(Server.scala:140)
	at com.worldpay.gateway.ziosim.KcatApp$.run(KcatApp.scala:70)
	at zio.ZIOApp.$anonfun$invoke$4(ZIOApp.scala:95)
	at zio.ZIO$FlatMap.apply(ZIO.scala:6182)
	at zio.ZIO$FlatMap.apply(ZIO.scala:6171)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:885)
	at zio.internal.FiberContext.run(FiberContext.scala:115)
	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
	at zio.internal.FiberContext.runUntil(FiberContext.scala:538)"_
```
The app runs correctly when deployed to Docker but not in Kubernetes / EKS. Given the nature of the error and the fact that it occurs at the intersection of zio-http (Server) and zio core library (ZManaged) is there a dependency mismatch?

**To Reproduce**

I may not provide full steps to reproduce as the deployment is a proprietary system, however:

Dependencies:
```
  lazy val zioHttp = "io.d11" %% "zhttp" % "2.0.0-RC2"
  lazy val zioCore = "dev.zio" %% "zio" % "2.0.0-RC2"
  lazy val zioStreams = "dev.zio" %% "zio-streams" % "2.0.0-RC2"
  lazy val zioProcess = "dev.zio" %% "zio-process" % "0.7.0-RC2"
  lazy val zioJson = "dev.zio" %% "zio-json" % "0.3.0-RC3"
  lazy val zioPrelude = "dev.zio" %% "zio-prelude" % "1.0.0-RC10"
```

MyApp.scala:
```
object MyApp extends ZIOAppDefault {

val middlewares: HttpMiddleware[Console with Clock, IOException] =
    Middleware.debug ++
      Middleware.timeout(3 seconds) ++
      Middleware.addHeader("X-Environment", "Dev")
...
def server: Server[Console with Clock, Throwable] =
    Server(route @@ middlewares)
      .withError(th => Console.printLineError(th.getMessage()).ignore)
      .withLeakDetection(LeakDetectionLevel.PARANOID)

  override def run: ZIO[ZEnv with ZIOAppArgs, Any, Any] = server.startDefault.exitCode
}
```

and then deploy to k8s

**Expected behavior**
The pod should deploy and run as it does in Docker.

**Desktop (please complete the following information):**
 - OS: Linux:ubuntu (AWS)
 - Browser : N/A

**Additional context**
The base image provides openjdk:11

**Comment by girdharshubham** [comment]
Thanks for raising this issue @etherline
We'll be taking a look at it.

In the meantime, could you let us know what do use for packaging the application?

Do you use `sbt-assembly` or `sbt-native-packager`?

**Comment by etherline** [comment]
Thanks for responding. I used:
"com.github.sbt" % "sbt-native-packager" % "1.9.7"
"se.marcuslonnberg" % "sbt-docker" % "1.8.2"

and generated the manifest using Helm. I've cherry picked the relevant parts of the generated manifest:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: RELEASE-NAME-kafka-dev-kafcat-zio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafcat-zio
    spec:
      containers:
        - name: kafcat-zio
          image: <repo_tag>:latest
          ports:
            - containerPort: 8093
        - name: cp-kafkacat
          image: confluentinc/cp-kafkacat
          command: ["/bin/sh"]
          args: ["-c", "trap : TERM INT; sleep infinity & wait"]

  selector:
    matchLabels:
      app: kafcat-zio
---

apiVersion: v1
kind: Service
metadata:
  name: kafcat-zio
  labels:
    app: kafcat-zio
spec:
  ports:
    - name: external
      port: 8093
      protocol: TCP
  selector:
    app: kafcat-zio

```

**Comment by tusharmath** [comment]
@etherline ZIO Http `2.0.0-RC2` depends on ZIO Core `2.0.0-RC1`. We will be releasing a new version in the coming week that will support RC2.

**Comment by etherline** [comment]
@tusharmath thank you for investigating this.
