### ISSUE TITLE
error serving file without known extension

### ISSUE THREAD

**Issue by enzief** [zio/zio-http#998]
**Version**
`1.0.0.0-RC24`

**Describe the bug**
Encode responses created from `HttpData.fromFile(???)` will throw NPE if the system's file type detectors cannot determine the file type.

**To Reproduce**
Steps to reproduce the behaviour:
1. `echo 'some text' > text_file` (no file extension)
2. Make app to server the file via `HttpData.fromFile(text_file)`
3. `curl ...`

**Expected behaviour**
The file is served no matter its content.

**Screenshots**
```
[info] 2022-02-09T23:01:57,508Z WARN  io.netty.channel.DefaultChannelPipeline  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[info] java.lang.NullPointerException: value
[info]  at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39)
[info]  at io.netty.handler.codec.DefaultHeaders.setObject(DefaultHeaders.java:479)
[info]  at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:183)
[info]  at zhttp.http.Response.unsafeEncode(Response.scala:86)
[info]  at zhttp.service.server.content.handlers.ServerResponseHandler.encodeResponse(ServerResponseHandler.scala:73)
[info]  at zhttp.service.server.content.handlers.ServerResponseHandler.channelRead0(ServerResponseHandler.scala:28)
[info]  at zhttp.service.server.content.handlers.ServerResponseHandler.channelRead0(ServerResponseHandler.scala:16)
[info]  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[info]  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[info]  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[info]  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[info]  at zhttp.service.Handler.unsafeRun(Handler.scala:88)
[info]  at zhttp.service.Handler.channelRead0(Handler.scala:26)
[info]  at zhttp.service.Handler.channelRead0(Handler.scala:14)
[info]  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
```

**Comment by nartamonov** [comment]
I suppose it was fixed in #883.
